export const restaurantList = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "551490",
      name: "Bakingo",
      uuid: "3e7b4ee9-0ee9-4d66-a59a-c037b40c2804",
      city: "54",
      area: "Shastri Nagar",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "otwz8qifqfvdjvt5qvfy",
      cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
      tags: [],
      costForTwo: 29900,
      costForTwoString: "₹299 FOR TWO",
      deliveryTime: 47,
      minDeliveryTime: 47,
      maxDeliveryTime: 47,
      slaString: "47 MINS",
      lastMileTravel: 4.400000095367432,
      slugs: {
        restaurant: "bakingo-meerut-shastri-nagar",
        city: "meerut",
      },
      cityState: "54",
      address:
        "106-107/9 First Floor Shashtri Nagar Meerut, Uttar Pradesh-250004",
      locality: "Gurudwara Road\n",
      parentId: 3818,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 2400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 3200,
        message: "",
        title: "Delivery Charge",
        amount: "3200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7354710~p=1~eid=00000189-54de-de8d-0991-1e4000a10121~srvts=1689346039437",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "4.4 kms",
      hasSurge: false,
      sla: {
        restaurantId: "551490",
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        lastMileTravel: 4.400000095367432,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.3",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "96468",
      name: "Kakkar's Kitchen",
      uuid: "262a0bdc-c116-48cc-bb6e-51d8c2c5d223",
      city: "54",
      area: "Shastri Nagar",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "ggorqt84gwmhctifbsza",
      cuisines: ["North Indian", "Chinese"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: "42 MINS",
      lastMileTravel: 3,
      slugs: {
        restaurant: "kakkars-kitchen-shastri-nagar-shastri-nagar",
        city: "meerut",
      },
      cityState: "54",
      address:
        "Hotel Rajhans Regency ,28, Panchsheel Colony, Garh Road, Shastri Nagar, Meerut",
      locality: "Panchsheel Colony",
      parentId: 15585,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "96468",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.8",
      totalRatings: 5000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "547132",
      name: "Citi Bakers",
      uuid: "25b47575-2e14-4a1d-ae35-ec6b1654ff6b",
      city: "54",
      area: "Shastri Nagar",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "su6jintge0lb61hv92ih",
      cuisines: ["Bakery", "Snacks"],
      tags: [],
      costForTwo: 10000,
      costForTwoString: "₹100 FOR TWO",
      deliveryTime: 42,
      minDeliveryTime: 42,
      maxDeliveryTime: 42,
      slaString: "42 MINS",
      lastMileTravel: 3.5,
      slugs: {
        restaurant: "citi-bakers-shastri-nagar-shastri-nagar",
        city: "meerut",
      },
      cityState: "54",
      address:
        "C-2/38 sector, Central Market, Shastri Nagar, Meerut, Ward No. 47 Shastri Nagar Scheme No. 7 Sec- 2, ZONE- 6, Meerut, Uttar Pradesh - 250004",
      locality: "Sector 2",
      parentId: 328639,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3.5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "547132",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        lastMileTravel: 3.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.6",
      totalRatings: 20,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "693674",
      name: "Cheesecake & co.",
      uuid: "939f536e-7ab6-409d-bb9b-26c6f0c20115",
      city: "54",
      area: "Shastri Nagar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "40b0a201eadbec469c2f9a06d5e7c722",
      cuisines: ["Bakery", "Desserts"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 47,
      minDeliveryTime: 47,
      maxDeliveryTime: 47,
      slaString: "47 MINS",
      lastMileTravel: 3.799999952316284,
      slugs: {
        restaurant: "cheesecake-&-co.-shastri-nagar-shastri-nagar",
        city: "meerut",
      },
      cityState: "54",
      address:
        "HOUSE NO -1094/2,SHASTRI NAGAR ,MEERUT , ZONE- 1, Meerut, Uttar Pradesh-250002",
      locality: "Sector 9",
      parentId: 387417,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7385745~p=4~eid=00000189-54de-de8d-0991-1e4100a10461~srvts=1689346039437",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3.7 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹150 OFF",
        subHeader: "ABOVE ₹399",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "693674",
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        lastMileTravel: 3.799999952316284,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "--",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "634710",
      name: "Goila Butter Chicken",
      uuid: "96116359-3a38-4713-9af5-0fb87a293afa",
      city: "54",
      area: "Shastri Nagar",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "5e19832da032dd69547565e27104706f",
      cuisines: ["North Indian", "Mughlai", "Biryani", "Indian"],
      tags: [],
      costForTwo: 60000,
      costForTwoString: "₹600 FOR TWO",
      deliveryTime: 44,
      minDeliveryTime: 44,
      maxDeliveryTime: 44,
      slaString: "44 MINS",
      lastMileTravel: 2.4000000953674316,
      slugs: {
        restaurant: "goila-butter-chicken-the-galleria-shastri-nagar",
        city: "meerut",
      },
      cityState: "54",
      address:
        "L-1, The Galleria, First Floor, Garh Road, Meerut Tehsil, Meerut, Uttar Pradesh, 250001",
      locality: "Garh Road",
      parentId: 322587,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.4 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "634710",
        deliveryTime: 44,
        minDeliveryTime: 44,
        maxDeliveryTime: 44,
        lastMileTravel: 2.4000000953674316,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.8",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "421932",
      name: "Sheetal Pay Bhandar",
      uuid: "3c6078d2-abbe-460a-9675-a4515e635c8c",
      city: "54",
      area: "Meerut Cantt",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "au7p5wd1lz21ndtd2vph",
      cuisines: ["Sweets", "Desserts"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 45,
      minDeliveryTime: 45,
      maxDeliveryTime: 45,
      slaString: "45 MINS",
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: "sheetal-pay-bhandar-partapur-partapur",
        city: "meerut",
      },
      cityState: "54",
      address:
        "102, Khair nagar, Pan Dariwa, Meerut City, Meerut, Uttar Pradesh, 250002",
      locality: "Partapur",
      parentId: 234711,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.2 kms",
      hasSurge: false,
      sla: {
        restaurantId: "421932",
        deliveryTime: 45,
        minDeliveryTime: 45,
        maxDeliveryTime: 45,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.9",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "420890",
      name: "Bhai Ji mast chaap wale",
      uuid: "71d2683a-8b35-4d89-9e7a-b578b51ab2de",
      city: "54",
      area: "Shastri Nagar",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "tli87ywjqrmajhnqvutv",
      cuisines: ["North Indian", "Chinese"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 55,
      minDeliveryTime: 55,
      maxDeliveryTime: 55,
      slaString: "55 MINS",
      lastMileTravel: 3,
      slugs: {
        restaurant: "bhai-ji-mast-chaap-wale-shastri-nagar-shastri-nagar",
        city: "meerut",
      },
      cityState: "54",
      address: "22/6, shop 7, sector 6, nai sadak, shashtri nagar, meerut",
      locality: "Sector 6",
      parentId: 234131,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7261332~p=7~eid=00000189-54de-de8d-0991-1e4200a10702~srvts=1689346039437",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "420890",
        deliveryTime: 55,
        minDeliveryTime: 55,
        maxDeliveryTime: 55,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.5",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "203462",
      name: "Kakkar's Chaap",
      uuid: "dc8a0079-2f71-4906-9d94-e0bcbc90f287",
      city: "54",
      area: "Panchsheel Colony",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "gr2pjl5crdai7l6pjcyy",
      cuisines: ["Tandoor", "North Indian", "Snacks"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 46,
      minDeliveryTime: 46,
      maxDeliveryTime: 46,
      slaString: "46 MINS",
      lastMileTravel: 2.5,
      slugs: {
        restaurant: "kakkar's-chaap-shastri-nagar-shastri-nagar",
        city: "meerut",
      },
      cityState: "54",
      address:
        "Hotel Rajhans Regency ,28, Panchsheel Colony, Garh Road, Shastri Nagar, Meerut",
      locality: "Garh Road",
      parentId: 15150,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "203462",
        deliveryTime: 46,
        minDeliveryTime: 46,
        maxDeliveryTime: 46,
        lastMileTravel: 2.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.9",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "421811",
      name: "Hangries",
      uuid: "dd4ddddf-b597-404d-a54f-afb2aa0e7adf",
      city: "54",
      area: "Panchsheel Colony",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "tejrc0zoypxmajbj5dlo",
      cuisines: ["American", "Italian", "Chinese"],
      tags: [],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 46,
      minDeliveryTime: 46,
      maxDeliveryTime: 46,
      slaString: "46 MINS",
      lastMileTravel: 3,
      slugs: {
        restaurant: "hangries-shastri-nagar-shastri-nagar",
        city: "meerut",
      },
      cityState: "54",
      address: "167/12 A, PANCHSHEEL COLONY, GARH ROAD, MEERUT-250001",
      locality: "Garh Road",
      parentId: 93241,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "421811",
        deliveryTime: 46,
        minDeliveryTime: 46,
        maxDeliveryTime: 46,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "126409",
      name: "Hotel Harmony Inn",
      uuid: "ac60c6af-7279-4321-819b-defcc4e7b330",
      city: "54",
      area: "Shastri Nagar",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "fkathfastya6zqrlg0hk",
      cuisines: [
        "Chinese",
        "North Indian",
        "Mughlai",
        "Punjabi",
        "Continental",
        "Italian",
        "Desserts",
      ],
      tags: [],
      costForTwo: 60000,
      costForTwoString: "₹600 FOR TWO",
      deliveryTime: 52,
      minDeliveryTime: 52,
      maxDeliveryTime: 52,
      slaString: "52 MINS",
      lastMileTravel: 3.700000047683716,
      slugs: {
        restaurant: "harmony-inn-garh-road-meerut-cantt",
        city: "meerut",
      },
      cityState: "54",
      address: "Property No.-147 and 148/2 at Main Garh Road",
      locality: "Garh Road",
      parentId: 15431,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7250541~p=10~eid=00000189-54de-de8d-0991-1e4300a10a36~srvts=1689346039437",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3.7 kms",
      hasSurge: false,
      sla: {
        restaurantId: "126409",
        deliveryTime: 52,
        minDeliveryTime: 52,
        maxDeliveryTime: 52,
        lastMileTravel: 3.700000047683716,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.7",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "366151",
      name: "Roll Singh",
      uuid: "b76c364f-4bee-481b-8f3d-cef81f34efc4",
      city: "54",
      area: "Shastri Nagar",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "m33qrlscwl4vwuijgoyn",
      cuisines: ["Snacks", "Beverages"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 46,
      minDeliveryTime: 46,
      maxDeliveryTime: 46,
      slaString: "46 MINS",
      lastMileTravel: 2.5,
      slugs: {
        restaurant: "roll-singh-shastri-nagar-shastri-nagar",
        city: "meerut",
      },
      cityState: "54",
      address:
        "SHOP NO.A-28, GROUND FLOOR, S2S,  SHOHRAB GATE, NEAR BUS STAND, Ward  No. 37 Shahpeer Gate, ZONE- 4, Meerut,  Uttar Pradesh - 250002",
      locality: "Garh Road",
      parentId: 170831,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "366151",
        deliveryTime: 46,
        minDeliveryTime: 46,
        maxDeliveryTime: 46,
        lastMileTravel: 2.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.5",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "95041",
      name: "Shree Fast Food",
      uuid: "189619a7-6b0e-45b1-a16c-5d6bdd97ad14",
      city: "54",
      area: "Shastri Nagar",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "hnylcdxdlmxqimklfd8p",
      cuisines: ["North Indian"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 47,
      minDeliveryTime: 47,
      maxDeliveryTime: 47,
      slaString: "47 MINS",
      lastMileTravel: 3.5,
      slugs: {
        restaurant: "shree-fast-food-central-market-vidya-nagar",
        city: "meerut",
      },
      cityState: "54",
      address: "Nai Sarak, Sector 3, Tejgarhi, Shastri Nagar, Meerut",
      locality: "Sector 3",
      parentId: 11355,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3.5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "95041",
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        lastMileTravel: 3.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.7",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "683580",
      name: "Sheetal Ji Chaap Waale",
      uuid: "f62cdfbf-ffde-424f-9e6c-1e7730062487",
      city: "54",
      area: "Shastri Nagar",
      totalRatingsString: "20+ ratings",
      cloudinaryImageId: "b139cc0e94645b50b1bca2bd8dced0cd",
      cuisines: [
        "North Indian",
        "Tandoor",
        "Chinese",
        "Snacks",
        "Desserts",
        "Beverages",
      ],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 53,
      minDeliveryTime: 53,
      maxDeliveryTime: 53,
      slaString: "53 MINS",
      lastMileTravel: 3,
      slugs: {
        restaurant: "sheetal-ji-chaap-waale-shastri-nagar-shastri-nagar",
        city: "meerut",
      },
      cityState: "54",
      address:
        "SHOP NO. 23/6, NAI SADAK, SHASTRI NAGAR, ZONE- 5, Meerut, Uttar Pradesh-250001",
      locality: "Nai Sadak",
      parentId: 407960,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7104059~p=13~eid=00000189-54de-de8d-0991-1e4400a10d4e~srvts=1689346039437",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹150 OFF",
        subHeader: "ABOVE ₹999",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "683580",
        deliveryTime: 53,
        minDeliveryTime: 53,
        maxDeliveryTime: 53,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.5",
      totalRatings: 20,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "267683",
      name: "Marwari Bhoj",
      uuid: "db79321a-feef-4f5c-9471-c426db3c7c0a",
      city: "54",
      area: "Devpuri",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "z7usyd8sfyyuya0m0j5e",
      cuisines: ["Indian"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 47,
      minDeliveryTime: 47,
      maxDeliveryTime: 47,
      slaString: "47 MINS",
      lastMileTravel: 2.5,
      slugs: {
        restaurant: "marwari-bhoj-partapur-partapur",
        city: "meerut",
      },
      cityState: "54",
      address: "Metro PLaza Baghpat Road, Meerut",
      locality: "Baghpat Road",
      parentId: 132881,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "2.5 kms",
      hasSurge: false,
      sla: {
        restaurantId: "267683",
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        lastMileTravel: 2.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.4",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "368179",
      name: "Pizza Hut",
      uuid: "d9928147-b0ec-40ee-b3d5-daa81e4b1a1f",
      city: "54",
      area: "Meerut Cantt",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
      cuisines: ["Pizzas"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 47,
      minDeliveryTime: 47,
      maxDeliveryTime: 47,
      slaString: "47 MINS",
      lastMileTravel: 3,
      slugs: {
        restaurant: "pizza-hut-garh-road-meerut-shastri-nagar",
        city: "meerut",
      },
      cityState: "54",
      address:
        "PIZZA HUT at Shop No- G-2, Ground Floor, Plot No- 372 and 372/1, Mohalla Panchsheel Colony, Garh Road, Meerut, Meerut, Uttar Pradesh-250002",
      locality: "Garh Road",
      parentId: 721,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 1900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 800,
            message: "",
          },
        ],
        totalFees: 2700,
        message: "",
        title: "Delivery Charge",
        amount: "2700",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "3 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹120",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "368179",
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "3.7",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
    crouton: {
      type: "SPECIAL",
      metaInfo: {
        bgColor: "#282C3F",
        icon: "surge_listing_piuzrv",
        textColor: "#ffffff",
        title: "High Demand",
        message: "Surge fee of Rs ₹8 may be applicable",
      },
    },
  },
];
